[project]
name = "so1"
version = "0.1.0"
description = "So1 Test"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.12",
    "asyncio>=3.4.3",
    "axios>=0.4.0",
    "openai>=1.61.1",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
]
